{
  "formatVersion": "1.1",
  "component": {
    "url": "../../common/0.0.1/common-0.0.1.module",
    "group": "com.yochidros",
    "module": "common",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-debug.aar",
          "url": "common-android-0.0.1-debug.aar",
          "size": 3382,
          "sha512": "f3baf03904dc5dc86ad821fc73cbdef711669183c0036b4aad341b1091b39388522538de20aa375738fe963f3d5be3b0b5716fe6509a06dcd362415b444cb51b",
          "sha256": "7674c7aea5f574e1bf0acd3c94396cf5db2e651c19358485515218876b8ad8bc",
          "sha1": "83e50608229d6c12b64f5bfaa4c0dbcc8fcca806",
          "md5": "e17b75dfa69db0478499270884286c19"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "common-debug.aar",
          "url": "common-android-0.0.1-debug.aar",
          "size": 3382,
          "sha512": "f3baf03904dc5dc86ad821fc73cbdef711669183c0036b4aad341b1091b39388522538de20aa375738fe963f3d5be3b0b5716fe6509a06dcd362415b444cb51b",
          "sha256": "7674c7aea5f574e1bf0acd3c94396cf5db2e651c19358485515218876b8ad8bc",
          "sha1": "83e50608229d6c12b64f5bfaa4c0dbcc8fcca806",
          "md5": "e17b75dfa69db0478499270884286c19"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-release.aar",
          "url": "common-android-0.0.1.aar",
          "size": 3282,
          "sha512": "5ef87d32ef3e2db966b0a0c1dbfb54cb37ed44414ad3120e9b0c470fad339a2bec0948d3e272f6d986fc9796e8a605af7eb207eec21b0e020f2239a70bcc244f",
          "sha256": "a74b1eab57f783f91d7a1823df708bdc88beadaf097a31bc00310bc485354dc3",
          "sha1": "54b1efc5cffc16ffb27c44b71bc10b7f9ea4f4b5",
          "md5": "38531bc149006ce5707296f98aa4fcee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "common-release.aar",
          "url": "common-android-0.0.1.aar",
          "size": 3282,
          "sha512": "5ef87d32ef3e2db966b0a0c1dbfb54cb37ed44414ad3120e9b0c470fad339a2bec0948d3e272f6d986fc9796e8a605af7eb207eec21b0e020f2239a70bcc244f",
          "sha256": "a74b1eab57f783f91d7a1823df708bdc88beadaf097a31bc00310bc485354dc3",
          "sha1": "54b1efc5cffc16ffb27c44b71bc10b7f9ea4f4b5",
          "md5": "38531bc149006ce5707296f98aa4fcee"
        }
      ]
    }
  ]
}
