{
  "formatVersion": "1.1",
  "component": {
    "url": "../../common/0.0.1/common-0.0.1.module",
    "group": "com.yochidros",
    "module": "common",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-debug.aar",
          "url": "common-android-0.0.1-debug.aar",
          "size": 2796,
          "sha512": "53f6afee728fc7c3dfdb618841ec3743cf939172ed9e784a06d700fd14e1ff9ea57563b5ff6af78689e612808cd6df6608f529db0096676d40a0b5904ec3889a",
          "sha256": "9a0678c68e78913833e2346ce6db083257cf1e615aa25acfed2dc2eb6cc666d4",
          "sha1": "ddaf08b2d1417cb43a15ca1ac8de4fca3e532e9c",
          "md5": "8a32cedc25d8bad4542034cd97bee052"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "common-debug.aar",
          "url": "common-android-0.0.1-debug.aar",
          "size": 2796,
          "sha512": "53f6afee728fc7c3dfdb618841ec3743cf939172ed9e784a06d700fd14e1ff9ea57563b5ff6af78689e612808cd6df6608f529db0096676d40a0b5904ec3889a",
          "sha256": "9a0678c68e78913833e2346ce6db083257cf1e615aa25acfed2dc2eb6cc666d4",
          "sha1": "ddaf08b2d1417cb43a15ca1ac8de4fca3e532e9c",
          "md5": "8a32cedc25d8bad4542034cd97bee052"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-release.aar",
          "url": "common-android-0.0.1.aar",
          "size": 2694,
          "sha512": "0ee086a46c93cb38d74a648efceee05608f55f643cc66cfa598796c938b9a9fdafc618a027f2a4d3858c3adddf05ec20269750944510a65836a60f878fe85e95",
          "sha256": "5968701f318583622256eb3a6138322f788c678cc8d7638c2851ad0a145131cb",
          "sha1": "0803e3948b05d4c3d80344acdd18417722ca68d4",
          "md5": "c7ab089b303535558702f2a0c978190f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "common-release.aar",
          "url": "common-android-0.0.1.aar",
          "size": 2694,
          "sha512": "0ee086a46c93cb38d74a648efceee05608f55f643cc66cfa598796c938b9a9fdafc618a027f2a4d3858c3adddf05ec20269750944510a65836a60f878fe85e95",
          "sha256": "5968701f318583622256eb3a6138322f788c678cc8d7638c2851ad0a145131cb",
          "sha1": "0803e3948b05d4c3d80344acdd18417722ca68d4",
          "md5": "c7ab089b303535558702f2a0c978190f"
        }
      ]
    }
  ]
}
